AssemblySoft.WonkaBuild/Controllers/BuildController.cs
using System;
using System.Configuration;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

using AssemblySoft.DevOps;
using AssemblySoft.WonkaBuild.Hubs;
using AssemblySoft.WonkaBuild.Models;
using AssemblySoft.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Configuration;

namespace AssemblySoft.WonkaBuild.Controllers
{
    public class BuildController : Controller
    {
        #region Constants
        //Files
        const string COMPLETED_DATA_FILE = "CompletedDataFile";
        const string ERROR_DATA_FILE = "ErrorDataFile";
        const string PROCESSING_DATA_FILE = "ProcessingDataFile";        
        const string BUILD_LOG_DATA_FILE = "BuildLogDataFile";
        const string FILE_WONKA_LOG = "WonkaLogFile";
        const string TASK_DEFINITIONS_ARCHIVE = "TaskDefinitionsArchive";

        //Filter
        const string TASKS_FILTER = "TasksFilter";

        //Session
        const string SESSION_KEY_RUN_PATH = "SessionRunPath";
        const string TASK_NAME = "SessionTaskName";

        #endregion

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewData["Message"] = "Ver 1.0.0";

            return View();
        }

        public ActionResult Help()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }


        #region Task Actions

        public ActionResult LoadHistory()
        {
            try
            {             
                
                AddMessage(BuildResources.Status_LoadingHistory);

                var model = LoadTaskHistory();
                if (model == null || !model.Any())
                {
                    AddMessage(BuildResources.Error_UnableToFindTaskHistoryToLoad);
                }
                else
                {
                    AddMessage(BuildResources.Status_CompletedLoadingHistory);
                }


                return PartialView("_LoadHistory", model.OrderByDescending(e => Number(e.Task.Project))); //order by project
            }
            catch (Exception e)
            {
                HandleException(e);
            }

            return PartialView("_LoadHistory");
        }

        public ActionResult LoadTasks()
        {
            try
            {
                AddMessage(BuildResources.Status_LoadingTasks);                
                var model = LoadTaskDefinitionsOrderByLatestVersion(-1);
                if (model == null || !model.Any())
                {
                    AddMessage(BuildResources.Error_UnableTofindTasksToLoad);
                }
                else
                {
                    AddMessage(BuildResources.Status_CompletedLoadingTasks);
                }

                //determine latest
                return PartialView("_LoadTasks", model);
            }
            catch (Exception e)
            {
                HandleException(e);
            }

            return PartialView("_LoadTasks");
        }

        public ActionResult LoadTasksByLatestVersion()
        {
            try
            {                
                AddMessage(BuildResources.Status_LoadingTasks);
                var model = LoadTaskDefinitionsOrderByLatestVersion(1);
                if (model == null || !model.Any())
                {
                    AddMessage(BuildResources.Error_UnableTofindTasksToLoad);
                }
                else
                {
                    AddMessage(BuildResources.Status_CompletedLoadingTasks);
                }

                //determine latest
                return PartialView("_LoadTasks", model);
            }
            catch (Exception e)
            {
                HandleException(e);
            }

            return PartialView("_LoadTasks");
        }

        public ActionResult Run(TaskModel taskModel)
        {
            var startTime = DateTime.Now;
            Session.Clear();

            AddMessage(BuildResources.Status_StartingBuild);
            string runPath = string.Empty;

            try
            {
                runPath = InitialiseBuildRun(taskModel.Path, taskModel.Project);

                Session[WebConfigurationManager.AppSettings[SESSION_KEY_RUN_PATH]] = runPath;
                Session[WebConfigurationManager.AppSettings[TASK_NAME]] = taskModel.Task;
            }
            catch (Exception e)
            {
                HandleException(e);
                return PartialView("_TasksFail");
            }


            var taskRunner = new TaskRunner(runPath);
            taskRunner.TaskStatus += (e) =>
            {
                AddMessage(e.Status);
            };

            taskRunner.TasksCompleted += (e) =>
            {
                while (Broadcaster.Instance.MessageCount > 1)
                {
                    Thread.Sleep(2000);
                }

                if (e.Status == TaskStatus.Faulted.ToString())
                {
                    System.IO.File.Create(Path.Combine(runPath, WebConfigurationManager.AppSettings[ERROR_DATA_FILE]));
                }
                else
                {
                    var timeTaken = DateTime.UtcNow - startTime;
                    System.IO.File.Create(Path.Combine(runPath, WebConfigurationManager.AppSettings[COMPLETED_DATA_FILE]));
                    
                    //ToDo:
                    //FileClient.WriteTextToFile(Path.Combine(runPath, COMPLETED_DATA_FILE), timeTaken.ToString());
                }

            };

            string tasksPath = string.Empty;

            try
            {
                CancellationTokenSource _cts = new CancellationTokenSource();
                var token = _cts.Token;

                Task t1 = new Task(() =>
                {
                    var path = Path.Combine(runPath, WebConfigurationManager.AppSettings[PROCESSING_DATA_FILE]);
                    System.IO.File.Create(Path.Combine(runPath, WebConfigurationManager.AppSettings[PROCESSING_DATA_FILE]));

                    tasksPath = Path.Combine(runPath, taskModel.FullName);

                    taskRunner.Run(token, Path.Combine(tasksPath));

                });

                Task t2 = t1.ContinueWith((ante) =>
                {
                }, TaskScheduler.FromCurrentSynchronizationContext());

                t1.Start();
            }
            catch (DevOpsTaskException ex)
            {
                HandleException(ex);
                return PartialView("_TasksFail");
            }
            catch (AggregateException ag)
            {
                HandleException(ag);
                return PartialView("_TasksFail");
            }
            catch (Exception ex)
            {
                HandleException(ex);
                return PartialView("_TasksFail");
            }
            finally
            {
                var tasks = taskRunner.GetDevOpsTaskWithState();
                //could serialize the state back to the tasks file for verification
                //taskRunner.S.SerializeTasksToFile(tasks, ConfigurationManager.AppSettings["tasksPath"]);
            }

            var model = new TaskInformationModel()
            {
                TaskName = taskModel.Task,
                TasksPath = taskModel.Path,
                TasksStartTime = startTime.ToString(),
            };

            return PartialView("_TasksRunning", model);
        }        

        public ActionResult TasksComplete()
        {
            return PartialView("_TasksComplete");
        }

        public ActionResult TasksSummary()
        {
            var runPath = GetRunPath();
            //var taskName = GetTaskName();
            if (!string.IsNullOrEmpty(runPath))
            {

                StringBuilder summaryBuilder = new StringBuilder();

                var logTxt = FileClient.ReadAllText(Path.Combine(runPath, WebConfigurationManager.AppSettings[FILE_WONKA_LOG]));
                if (!string.IsNullOrEmpty(logTxt))
                {
                    summaryBuilder.AppendFormat("Wonka Log {0} {1}", Environment.NewLine, logTxt);
                }


                var processingTxt = FileClient.ReadAllText(Path.Combine(runPath, WebConfigurationManager.AppSettings[PROCESSING_DATA_FILE]));
                if (!string.IsNullOrEmpty(processingTxt))
                {
                    summaryBuilder.AppendFormat("Processing Log {0} {1}", Environment.NewLine, processingTxt);
                }

                var errorTxt = FileClient.ReadAllText(Path.Combine(runPath, WebConfigurationManager.AppSettings[ERROR_DATA_FILE]));
                if (!string.IsNullOrEmpty(processingTxt))
                {
                    summaryBuilder.AppendFormat("Error Log {0} {1}", Environment.NewLine, errorTxt);
                }


                var model = new TaskSummaryModel()
                {
                    BuildLabel = "build x.x.x.",
                    BuildTime = "2 minutes",
                    BuildLog = summaryBuilder.ToString(),
                };

                return PartialView("_TasksSummary", model);
            }

            return PartialView("_TasksSummary");
        }

        public ActionResult TasksFail()
        {
            Session.Clear();
            return PartialView("_TasksFail");
        }

        /// <summary>
        /// Retrieves the status of the task run
        /// </summary>
        /// <returns></returns>
        public JsonResult GetStatus()
        {
            var d_status = GetTaskStatus();
            var d_detailsMarkup = GetDetails(d_status);

            dynamic data = new
            {
                status = d_status.ToString(),
            };

            return Json(data);
        }

        #endregion
        

        private string GetDetails(DevOpsTaskStatus d_status)
        {

AssemblySoft.WonkaBuild/Views/Build/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>


<p>Starting point for consuming AssemblySoft.DevOps on NuGet</p>
<strong>Support:</strong> <a href="http://www.nuget.org/packages/AssemblySoft.DevOps/">See in the Nuget Gallery</a><br />   
<div class="nuget-badge">
    <p>
        <code>
            Install-Package AssemblySoft.DevOps
        </code>
    </p>
</div> 

AssemblySoft.WonkaBuild/Views/Build/Help.cshtml
@{
    ViewData["Title"] = "Help";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

AssemblySoft.WonkaBuild/Views/Build/Index.cshtml
@{
    ViewData["Title"] = "Wonka Tasks";
}

<div id="divResult">
</div>
<div style="margin-top:10px; margin-bottom:10px">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#build">Latest Tasks <i class="fa fa-cog fa-2x" aria-hidden="true"></i></a></li>
        <li><a class="tasks-all" data-toggle="tab" href="#all">All Tasks <i class="fa fa-cogs fa-2x" aria-hidden="true"></i></a></li>
        <li><a class="task-history" data-toggle="tab" href="#history">History <i class="fa fa-history fa-2x" aria-hidden="true"></i></a></li>
        <li><a class="task-debug" data-toggle="tab" href="#debug">Debug <i class="fa fa-bug fa-2x" aria-hidden="true"></i></a></li>
    </ul>
</div>
<div class="tab-content">
    <div id="build" class="tab-pane fade in active">

        <div id="tasksDiv" class="task-list">
            <div id="taskList">
            </div>
        </div>

        <!-- Idle, Running, Complete etc.-->
        <div id="status">
            <h4>Status: Idle</h4>
        </div>
        <!-- - X OK-->
        <div id="progressSpinner">
            <div id="progressDiv">
            </div>
        </div>
        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                            Console
                        </a>
                        <a href="#" class="btn btn-default clearConsole"><i class="fa fa-eraser" aria-hidden="true"></i></a>
                    </h4>
                </div>
                <div id="collapse1" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <div class="console">
                            <ul id="messages"></ul>
                        </div>
                    </div>
                </div>
            </div>


            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                            Build Log
                        </a>
                    </h4>
                </div>
                <div id="collapse2" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div id="buildLogDiv">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="all" class="tab-pane fade">
        <div id="allTasksDiv">
            <div id="allTasks">
            </div>
        </div>
    </div>

    <div id="history" class="tab-pane fade">
        <div id="tasksHistoryDiv">
            <div id="taskHistory">
            </div>
        </div>
    </div>
   
    <div id="debug" class="tab-pane fade">
            <div>Debug Info</div>
        </div>
</div>

<!-- Modal -->
<div id="taskDefModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg" style="width:65%;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Task Information</h4>
            </div>
            <div class="modal-body">
                <div id="taskDefinitionModalBody">
                    <p>Task Information.</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<!--end modal-->

<script>
function CheckStatus() {
    var options = {};
    options.url = '@Url.Action("GetStatus", "Build")';
    options.type = "POST";
    options.dataType = "json";
    options.contentType = "application/json";
    options.success = function (data) {

    $("#status").html("<h4>Status: " + data.status + "</h2> ");

    var $progress = $('#progressDiv');

    if (data.status == 'Idle' || data.status == 'Running') {
        setTimeout(CheckStatus, 2000);
    }
    else {


        if (data.status == 'Completed') {
            $.get('/build/taskscomplete', function (data) {
                $progress.replaceWith(data);

                $('.active-task').removeClass('fa-refresh fa-spin active-task').addClass('fa-check').addClass('completed');
                $('.run-task').removeClass('disabled');


            });
        }
        else {
            $.get('/build/tasksfail', function (data) {
                $progress.replaceWith(data);

                $('.active-task').removeClass('fa-refresh fa-spin active-task').addClass('fa-times').addClass('faulted');
                $('.run-task').removeClass('disabled');

            });
        }

        $rows = $('table.table tr');
        $rows.removeClass('.active');
        $rows.show(3000);

        var $buildLog = $('#buildLogDiv');
        $.get('/build/taskssummary', function (data) {
            $buildLog.replaceWith(data);

        });

    }
    };

    $.ajax(options)
    }

</script>

AssemblySoft.WonkaBuild/Views/Build/_LoadHistory.cshtml
@model IEnumerable<AssemblySoft.WonkaBuild.Models.TaskHistory>

@if (Model != null)
{

    <table class="table table-striped table-bordered table-hover table-condensed">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Task.Task)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Task.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            
            <th>
               
            </th>
            
        </tr>

        @foreach (var item in Model)
        {
            <tr class="task-row">
                <td>
                    @Html.DisplayFor(modelItem => item.Task.Task)
                </td>
               
                <td>

                    @if (item.Summary != null)
                    {
                        @Html.DisplayFor(modelItem => item.Summary.BuildLog)
                    }
                    else
                    {
                        @Html.Raw("N/A")
                    }
                </td>
                <td>
                    @Html.Raw(item.Status)                    
                </td>
                <td>
                    <a class="btn btn-primary task-info" href="#" data-toggle="modal" data-target="#taskDefModal">
                        <div><i class="fa fa-info-circle fa-2x"></i></div>
                    </a>

                    <div class="info-header" style="display:none">
                        @item.Task.Task Workflow History
                    </div>
                    <div class="info-body" style="display:none">
                        <xmp>
                            @Html.Raw(item.Task.Definition)
                        </xmp>
                    </div>
                </td>
            </tr>
        }

    </table>
}
else
{
    <h3>No Tasks history available </h3>
}

AssemblySoft.WonkaBuild/Views/Build/_LoadTasks.cshtml
@model IEnumerable<AssemblySoft.WonkaBuild.Models.TaskModel>
@if (Model != null)
{

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Task)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Version)
            </th>
            <th>
                Actions
            </th>

            <th>
                Status
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr class="task-row">
                <td>
                    @Html.DisplayFor(modelItem => item.Task)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Project)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Version)
                </td>
                <td>
                    <a data-url='@Url.Action("Run","Build", new { Task=item.Task, Path = item.Path, /* id=item.PrimaryKey */ Project = item.Project, FullName = item.FullName })' class="run-task btn btn-primary" href="#">
                        <div><i class="fa fa-play-circle fa-2x"></i></div>
                    </a>
                    <a class="btn btn-primary task-info" href="#" data-toggle="modal" data-target="#taskDefModal">
                        <div><i class="fa fa-info-circle fa-2x"></i></div>
                    </a>
                    <div class="info-header" style="display:none">
                        @item.Task Workflow
                    </div>
                    <div class="info-body" style="display:none">
                        <xmp>
                            @Html.Raw(item.Definition)
                        </xmp>
                    </div>
                </td>
                <td>
                    <i class="status fa fa-2x"></i>
                </td>

            </tr>
        }
    </table>
}
else
{
    <h3>No Tasks definitions available </h3>
}

AssemblySoft.WonkaBuild/Views/Build/_TasksComplete.cshtml
<div id="progressDiv">
    @*<i class="fa fa-check fa-2x fa-fw"></i>
    <span class="sr-only">Complete...</span>*@
</div>

AssemblySoft.WonkaBuild/Views/Build/_TasksFail.cshtml
<div id="progressDiv">
    @*<i class="fa fa-times fa-2x fa-fw" aria-hidden="true" fa-5x></i>
    <span class="sr-only">An error has occured...</span>*@
</div>

AssemblySoft.WonkaBuild/Views/Build/_TasksRunning.cshtml
@model AssemblySoft.WonkaBuild.Models.TaskInformationModel

<div id="taskInformation">
    @if (Model != null)
    {
        <p>
            Name: @Model.TaskName Start: @Model.TasksStartTime  Path:@Model.TasksPath
        </p>
    }
    else
    {
        <h2>Unable to load Task Information</h2>
    }
</div>

<div id="progressDiv">
    @*<i class="fa fa-refresh fa-spin fa-2x fa-fw"></i>
    <span class="sr-only">Running Tasks...</span>*@
</div>

AssemblySoft.WonkaBuild/Views/Build/_TasksSummary.cshtml
@model AssemblySoft.WonkaBuild.Models.TaskSummaryModel

<div id="progressDiv">
    <i class="fa fa-info" aria-hidden="true"></i>
    <span class="sr-only">Summary details...</span>
    @if (Model != null)
    {
        <h3>Label:</h3>
        <p>@Model.BuildLabel</p>

        <h3>Build Time:</h3>
        <p>@Model.BuildTime</p>

        <h3>Wonka Log:</h3>
        <p>@Model.BuildLog</p>
    }
    else
    {
        <h2>Unable to load Task Summary</h2>
    }
</div>